### ISSUE TITLE
I have a few questions.

### ISSUE THREAD

**Issue by densevoid** [jiaozi158/ShellFurURP#1]
Hello, can I ask a few questions? I would like the borders of each layer to gradually become transparent instead of abruptly ending, and I also want the shade of each layer to change gradually.

I see similar settings in the "Physical Hair Material Settings" section, but changing these settings doesn't seem to have any effect. Are these the settings I need? And why am I not seeing any changes from adjusting them? I am using Unity version 2022.3.7f1 and when I run your project, I get a series of warnings. However, everything else seems to be working fine.

**Comment by densevoid** [comment]
I realized that for the gradient it was necessary to switch to Physical Hair

**Comment by jiaozi158** [comment]
> I would like the borders of each layer to gradually become transparent instead of abruptly ending,

Hi, I think you're trying to achieve semi-transparent fur borders (changing the **fur cutout** property with a range slider), which is a useful feature to consider.

However, semi-transparent objects doesn't work well with some URP features (SSAO, Depth of Field, ...), so I decided to keep it opaque when publishing this repo.

Thank you for the feedback. I'll consider adding this feature when I have time.
