### ISSUE TITLE
Instancing Not Supported In Depth/DepthNormals

### ISSUE THREAD

**Issue by FragileDeviations** [jiaozi158/ShellFurURP#2]
I'm trying to use this in a VR project, however, when compiling the shader variants, these 2 errors come up:
```
Shader error in 'Universal Render Pipeline/Fur/Shell/Lit': gs_4_0 does not allow instancing at Assets/Mods/Avatars/Mae/Shaders/Shell/Depth.hlsl(153) (on d3d11)
Shader error in 'Universal Render Pipeline/Fur/Shell/Lit': gs_4_0 does not allow instancing at Assets/Mods/Avatars/Mae/Shaders/Shell/DepthNormals.hlsl(165) (on d3d11)
```

In game, anything in the depth texture becomes visible on objects with the shader in only the right eye. In the left eye, it looks normal.

I am not sure if it is specific to the fork of the URP I am using, I have not tested in a standard URP project.
I am using [Stress Level Zero's URP](https://github.com/StressLevelZero/Custom-RenderPipelineCore).

**Comment by jiaozi158** [comment]
Hi, thank you for reporting this issue!

It seems that I mistakenly kept the code snippet ```#pragma multi_compile _ _GEOM_INSTANCING``` on fallback passes of Depth & DepthNormals.

Could you try testing the fix in your project and see if it works?

By the way, I suggest using [multi-pass fur shader](https://github.com/jiaozi158/ShellFurURP/blob/main/Assets/Shaders/MultiPassShell/Lit-MP.shader) provided in this repo if the device doesn't support geometry shader instancing (```More Shell Amount``` in the fur material).

**Comment by FragileDeviations** [comment]
This fixed it, thanks. I would use the multi-pass shader, however the URP is specifically designed for singlepass.

**Comment by FragileDeviations** [comment]
This seems to be back, I didn't notice it in editor but in game it's still messed up. I have an image of it.
There's no errors when compiling either.
![image](https://github.com/jiaozi158/ShellFurURP/assets/30084485/be767011-a527-4122-bf0d-4cf14c4a5489)

**Comment by FragileDeviations** [comment]
Now it seems more of a problem with the HBAO package (screen space ambient occlusion) rather than depth.

**Comment by jiaozi158** [comment]
Maybe it's caused by some kind of down-sampling in the HBAO.
<img width="230" alt="image" src="https://github.com/jiaozi158/ShellFurURP/assets/62869447/f476a972-4e97-470c-813a-ff1c4bc69f44">

I suggest checking the rendering (shader textures) in [RenderDoc](https://docs.unity3d.com/Manual/RenderDocIntegration.html) or [Frame Debugger](https://docs.unity3d.com/Manual/frame-debugger-window.html) in build.

**Comment by FragileDeviations** [comment]
Unfortunately because it is a mod of an existing game I cannot get the project, however I can just install HBAO myself and try in editor, when I can afford HBAO.
Without HBAO enabled, the issue is gone, and HBAO at lower quality settings is less noticable.

**Comment by jiaozi158** [comment]
Does this still happen on objects with other shaders? (ex. URP Lit)

If it's only happening with `Shell Lit`, you can try disabling the (screen space) AO evaluation in fur shader by:

- Open the fur shader in use (Lit.shader or Lit-MP.shader)
- Comment out all lines with `#pragma multi_compile_fragment _ _SCREEN_SPACE_OCCLUSION`

**Comment by FragileDeviations** [comment]
It only happens with Shell Lit, not other shaders. URP Lit works fine with it, likely because SLZ modified the URP Lit shader for their custom URP.
Tried commenting out anything with _SCREEN_SPACE_OCCLUSION and it appears to now be fine, just darker than other objects until the HBAO setting is disabled, then all objects are darker.

**Comment by FragileDeviations** [comment]
This was specifically a problem in the right eye, so it's just something with stereo rendering and the SSAO likely.

**Comment by jiaozi158** [comment]
> This was specifically a problem in the right eye, so it's just something with stereo rendering and the SSAO likely.

Thank you for the info. I will try if I can reproduce the problem with URP SSAO in SLZ's custom pipeline later.

For now, I suggest commenting out the related keywords as a temporary solution.

**Comment by FragileDeviations** [comment]
Yeah commenting out those lines made it work.
These are the packages for SLZ's URP:
https://github.com/StressLevelZero/Custom-RenderPipelineCore.git#e9a22782f526ddd18e2e068908d08abe7ce2a16c
https://github.com/StressLevelZero/Custom-URP#bonelab

**Comment by jiaozi158** [comment]
Hi, I spent some time fixing the Geometry Shell method (currently less problematic on XR). Could you try testing it when you have time?

**Comment by FragileDeviations** [comment]
This fixed it, thanks!
