### ISSUE TITLE
Issue with Unity's forward+ rendering path

### ISSUE THREAD

**Issue by ianohare** [jiaozi158/ShellFurURP#3]
The model shows up pink in URP forward+ rendering path in Unity 2023.2

**Comment by jiaozi158** [comment]
Thank you for reporting the issue, and I'll fix it as soon as I have time!

While waiting for the fix, you may try disabling "Marschner Specular" to see if that temporarily resolves the issue.

**Comment by jiaozi158** [comment]
Hi, the issue should be fixed now.

**Comment by ianohare** [comment]
Yep, seems fixed now, thanks!
